# Generated by Django 4.2 on 2024-11-23 11:31

from django.db import migrations
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ('article_generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=1536),
        ),
    ]
