# Generated by Django 4.2 on 2024-11-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_generator', '0004_cluster_centroid_alter_article_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='published_at',
            field=models.DateTimeField(null=True),
        ),
    ]
