# Generated by Django 4.2 on 2024-11-23 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_generator', '0005_news_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='confidence_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='article',
            name='used_news',
            field=models.ManyToManyField(null=True, to='article_generator.news'),
        ),
    ]
